/// This is a Rust program that prices options using Black-Scholes model.
/// Reads option chain data from CSV files generated by the Python script.
mod visualization;

use serde::Deserialize;
use statrs::distribution::{ContinuousCDF, Normal};
use std::env;
use std::error::Error;
use std::f64::consts::E;
use std::fs::File;
use std::io::BufReader;
use visualization::{ChartPoint, VisualizationConfig};

#[derive(Debug, Deserialize)]
struct OptionData {
    strike: f64,
    #[serde(rename = "lastPrice")]
    last_price: f64,
    bid: Option<f64>,
    ask: Option<f64>,
    volume: Option<f64>,
    #[serde(rename = "openInterest")]
    open_interest: Option<f64>,
    #[serde(rename = "impliedVolatility")]
    implied_volatility: f64,
    #[serde(rename = "BS_current_price")]
    bs_current_price: f64,
    #[serde(rename = "BS_time_to_expiry_years")]
    bs_time_to_expiry_years: f64,
    #[serde(rename = "BS_risk_free_rate")]
    bs_risk_free_rate: f64,
    #[serde(rename = "BS_dividend_yield")]
    bs_dividend_yield: f64,
}

#[derive(Debug, Clone, Copy)]
enum OptionType {
    Call,
    Put,
}

struct BlackScholes {
    s: f64,  // Stock price
    k: f64,  // Strike price
    r: f64,  // Risk-free rate
    sigma: f64,  // Volatility
    t: f64,  // Time to expiration
    q: f64,  // Dividend yield
}

impl BlackScholes {
    fn new(s: f64, k: f64, r: f64, sigma: f64, t: f64) -> Self {
        Self {
            s,
            k,
            r,
            sigma,
            t,
            q: 0.0,  // Default to no dividend
        }
    }

    fn with_dividend(mut self, q: f64) -> Self {
        self.q = q;
        self
    }

    fn d1(&self) -> f64 {
        (self.s / self.k).ln() + (self.r - self.q + 0.5 * self.sigma.powi(2)) * self.t
    }

    fn d2(&self) -> f64 {
        self.d1() - self.sigma * self.t.sqrt()
    }

    fn price(&self, option_type: OptionType) -> f64 {
        let d1 = self.d1();
        let d2 = self.d2();

        let normal = Normal::new(0.0, 1.0).unwrap();

        match option_type {
            OptionType::Call => {
                self.s * E.powf(-self.q * self.t) * normal.cdf(d1)
                    - self.k * E.powf(-self.r * self.t) * normal.cdf(d2)
            }
            OptionType::Put => {
                self.k * E.powf(-self.r * self.t) * normal.cdf(-d2)
                    - self.s * E.powf(-self.q * self.t) * normal.cdf(-d1)
            }
        }
    }
}

fn main() -> Result<(), Box<dyn Error>> {
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        eprintln!("Usage: {} <csv_file_path>", args[0]);
        eprintln!("Example: {} AAPL_2026-03-02_20260228_113854_calls.csv", args[0]);
        std::process::exit(1);
    }

    let csv_path = &args[1];
    println!("Reading option chain data from: {}", csv_path);
    println!("{:=<80}", "");

    // Read CSV file
    let file = File::open(csv_path)?;
    let reader = BufReader::new(file);
    let mut csv_reader = csv::Reader::from_reader(reader);

    // Collect option data
    let mut options: Vec<OptionData> = Vec::new();

    for result in csv_reader.deserialize() {
        let option: OptionData = result?;
        options.push(option);
    }

    if options.is_empty() {
        eprintln!("No option data found in CSV file");
        std::process::exit(1);
    }

    // Get Black-Scholes parameters from first row
    let current_price = options[0].bs_current_price;
    let time_to_expiry = options[0].bs_time_to_expiry_years;
    let risk_free_rate = options[0].bs_risk_free_rate;
    let dividend_yield = options[0].bs_dividend_yield;

    println!("Black-Scholes Parameters:");
    println!("  Current Price (S): ${:.2}", current_price);
    println!("  Time to Expiry (T): {:.4} years", time_to_expiry);
    println!("  Risk-Free Rate (r): {:.4} ({:.2}%)", risk_free_rate, risk_free_rate * 100.0);
    println!("  Dividend Yield (q): {:.4} ({:.2}%)", dividend_yield, dividend_yield * 100.0);

    println!("\n{:=<80}", "");
    println!("Option Chain Analysis:");
    println!("{:=<80}", "");
    println!("{:<10} {:<12} {:<12} {:<12} {:<15}",
             "Strike", "Market", "Theoretical", "Difference", "IV");
    println!("{:-<80}", "");

    // Analyze each option
    for option in &options {
        let strike = option.strike;
        let market_price = option.last_price;
        let iv = option.implied_volatility;

        // Calculate theoretical price using Black-Scholes
        let bs = BlackScholes::new(
            current_price,
            strike,
            risk_free_rate,
            iv,
            time_to_expiry,
        ).with_dividend(dividend_yield);

        let theoretical_price = bs.price(OptionType::Call);
        let difference = market_price - theoretical_price;
        let diff_pct = (difference / theoretical_price) * 100.0;

        println!("${:<9.2} ${:<11.2} ${:<11.2} ${:+<11.2} ({:+.1}%)  {:.1}%",
                 strike, market_price, theoretical_price, difference, diff_pct, iv * 100.0);
    }

    // Find ATM option
    let atm_option = options.iter()
        .min_by(|a, b| {
            (a.strike - current_price).abs().partial_cmp(&(b.strike - current_price).abs()).unwrap()
        });

    if let Some(atm) = atm_option {
        println!("\n{:=<80}", "");
        println!("At-The-Money Option Analysis (Strike: ${:.2})", atm.strike);
        println!("{:=<80}", "");

        let bs = BlackScholes::new(
            current_price,
            atm.strike,
            risk_free_rate,
            atm.implied_volatility,
            time_to_expiry,
        ).with_dividend(dividend_yield);

        let theoretical_call = bs.price(OptionType::Call);
        let theoretical_put = bs.price(OptionType::Put);

        let volume_str = match atm.volume {
            Some(v) => format!("{:.0}", v),
            None => "N/A".to_string(),
        };

        let oi_str = match atm.open_interest {
            Some(oi) => format!("{:.0}", oi),
            None => "N/A".to_string(),
        };

        println!("  Market Price:        ${:.2}", atm.last_price);
        println!("  Theoretical (Call):  ${:.2}", theoretical_call);
        println!("  Theoretical (Put):   ${:.2}", theoretical_put);
        println!("  Difference (Call):   ${:+.2} ({:+.1}%)",
                 atm.last_price - theoretical_call,
                 ((atm.last_price - theoretical_call) / theoretical_call) * 100.0);
        println!("  Implied Volatility:  {:.2}%", atm.implied_volatility * 100.0);
        println!("  Volume:              {}", volume_str);
        println!("  Open Interest:       {}", oi_str);
    }

    println!("\n{:=<80}", "");
    println!("Analysis Complete");
    println!("{:=<80}", "");

    // Generate visualizations
    println!("\n{:=<80}", "");
    println!("Generating Visualizations...");
    println!("{:=<80}", "");

    // Prepare chart data
    let chart_data: Vec<ChartPoint> = options
        .iter()
        .map(|option| {
            let bs = BlackScholes::new(
                current_price,
                option.strike,
                risk_free_rate,
                option.implied_volatility,
                time_to_expiry,
            )
            .with_dividend(dividend_yield);

            ChartPoint {
                strike: option.strike,
                market_price: option.last_price,
                theoretical_price: bs.price(OptionType::Call),
                implied_volatility: option.implied_volatility,
                volume: option.volume,
            }
        })
        .collect();

    // Extract ticker from filename
    let ticker = csv_path
        .split('_')
        .next()
        .unwrap_or("UNKNOWN")
        .replace("/", "");

    let config = VisualizationConfig {
        ticker,
        current_price,
        time_to_expiry,
        historical_volatility: None, // Could be added from CSV if available
    };

    // Generate all charts
    if let Err(e) = visualization::generate_dashboard(&chart_data, &config, "charts") {
        eprintln!("Warning: Failed to generate visualizations: {}", e);
    }

    // Also generate volume analysis if data is available
    if chart_data.iter().any(|d| d.volume.is_some()) {
        if let Err(e) = visualization::plot_volume_analysis(
            &chart_data,
            &config,
            &format!("charts/{}_volume_analysis.png", config.ticker),
        ) {
            eprintln!("Warning: Failed to generate volume analysis: {}", e);
        }
    }

    println!("\n{:=<80}", "");

    Ok(())
}
